# This is a basic workflow to help you get started with Actions

name: Github Actions 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: AWS credentials configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIARBVSOWQGEZN46X4O
          aws-secret-access-key: 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
          aws-region: ap-south-1

      # Runs a set of commands using the runners shell
      - name: HashiCorp - Install Terraform
        uses: hashicorp/setup-terraform@v2.0.0
